export const EnvConfiguration = () => ({
  environment: process.env.NODE_ENV || 'dev',
  port: Number(process.env.PORT),
  defaultLimit: Number(process.env.DEFAULT_LIMIT),
  dbPassword: process.env.DB_PASSWORD,
  dbName: process.env.DB_NAME,
  dbPort: Number(process.env.DB_PORT),
  dbUser: process.env.DB_USER,
  dbHost: process.env.DB_HOST,
  dbSync: process.env.DB_SYNC,
  cachePort: Number(process.env.CACHE_PORT),
  cacheHost: process.env.CACHE_HOST,
  cacheTtl: process.env.CACHE_TTL,
  secretToken: process.env.SECRET_TOKEN,
  appRateShortTtl: Number(process.env.APP_RATE_SHORT_TTL),
  appRateShortLimit: Number(process.env.APP_RATE_SHORT_LIMIT),
  appRateMediumTtl: Number(process.env.APP_RATE_MEDIUM_TTL),
  appRateMediumLimit: Number(process.env.APP_RATE_MEDIUM_LIMIT),
  appRateLongTtl: Number(process.env.APP_RATE_LONG_TTL),
  appRateLongLimit: Number(process.env.APP_RATE_LONG_LIMIT),
  stage: process.env.STAGE,
  cloudName: process.env.CLD_CLOUD_NAME,
  cloudApiKey: process.env.CLD_API_KEY,
  cloudApiSecret: process.env.CLD_API_SECRET,
});
