name: Run integration testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: 22

jobs:
  unit-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm install

      - name: Run Unit testing
        run: |
          npm run test:unit

#   notify:
#     runs-on: ubuntu-latest
#     needs: unit-test
#     if: always()

#     steps:
#       - name: notify to slack
#         uses: 8398a7/action-slack@v3
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
#         with:
#           status: ${{ job.status }}
#           fields: repo,commit,author,job,took
